### PR TITLE
Mysql

### PR DESCRIPTION
**Pull request by shakdoesgithub**

### CODE REVIEW

**Comment by kran0** [comment]
@shakdoesgithub, thanks for your work and practical use of the image.
Unfortunately, I cannot directly place arbitrarily licensed binary artifacts in my repo due to possible license restrictions.

I will see what can be done with your implementation.
Seems, I must implement some kind of downloader, which will get all the depencies during build process.

Thanks for your work.

**Comment by shakdoesgithub** [comment]
Hey sorry about that. 
I was trying to open the PR against my fork of your awesome work.

If you want, I can do another PR for this, but this is just adding capturing CS stats to mysql.

Again, this was a mistake :\

**Comment by kran0** [comment]
Please do. Thank you.

**Comment by kran0** [comment]
@shakdoesgithub Just in case you are the practical user of the image, would you please add also some usage notes to the Readme. Quick how-to or such.

**Pull request closed without merging**
